# Generated by Django 4.2a1 on 2023-01-24 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0002_habit_tracker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="tracker",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="tracker",
            constraint=models.UniqueConstraint(
                fields=("date", "habit"), name="unique_for_habit_and_date"
            ),
        ),
    ]
